# Molecule managed

{% raw %}{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# install minimal packages for debian slim images
RUN apt-get update && \
    apt-get install -y python sudo bash ca-certificates iproute2 systemd systemd-sysv python3-pip && \
    apt-get clean{% endraw %}
